"""
make_jcim_package.py - assembles the upload package for J. Chem. Inf. Model.

usage: python src/make_jcim_package.py
writes manuscript/journal_package/:
  Manuscript.docx              figures embedded, as ACS accepts for initial submission
  Supporting_Information.pdf   Tables S1-S5
  Figure1.tif ... Figure6.tif  600 dpi RGB TIFF
  TOC_Graphic.tif              3.25 x 1.75 in table-of-contents graphic
  Cover_Letter.docx
  CHECKLIST.md                 automatic checks + what the author must still do
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

from docx import Document
from PIL import Image

BASE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE.parent))
from check_citation_order import first_citations  # noqa: E402

SOFFICE = Path(r"C:\Program Files\LibreOffice\program\soffice.exe")
SUB = BASE / "manuscript" / "submission"
OUT = BASE / "manuscript" / "journal_package"


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    ms, si = SUB / "Manuscript_Audit_JCIM.docx", SUB / "Supporting_Information_Audit_JCIM.docx"
    shutil.copy(ms, OUT / "Manuscript.docx")
    shutil.copy(SUB / "Cover_Letter_JCIM.docx", OUT / "Cover_Letter.docx")
    subprocess.run([str(SOFFICE), "--headless", "--convert-to", "pdf", "--outdir", str(OUT), str(si)],
                   check=True, capture_output=True, timeout=300)
    (OUT / f"{si.stem}.pdf").rename(OUT / "Supporting_Information.pdf")

    figs = sorted((BASE / "figures").glob("Fig[0-9]*.tif"), key=lambda f: int(re.findall(r"\d+", f.stem)[0]))
    info = []
    for f in figs + [BASE / "figures" / "TOC.tif"]:
        im = Image.open(f)
        dpi = float(im.info.get("dpi", (0, 0))[0])
        info.append((f.name, dpi, im.size[0] / dpi, im.size[1] / dpi))
        name = "TOC_Graphic.tif" if f.stem == "TOC" else f.name.replace("Fig", "Figure")
        im.convert("RGB").save(OUT / name, dpi=(dpi, dpi), compression="tiff_lzw")

    doc = Document(ms)
    ps = [p.text for p in doc.paragraphs]
    text = "\n".join(ps)
    abstract = ps[ps.index("Abstract") + 1]
    order = first_citations(str(ms))
    caps = [p for p in ps if re.match(r"^Figure \d+\.", p)]
    si_cited = sorted(set(re.findall(r"Table S(\d+)", text.split("\nAssociated Content")[0])))
    nrefs = sum(1 for p in ps if re.match(r"^\(\d+\) ", p))
    toc = next(i for i in info if i[0] == "TOC.tif")
    width = {n: w for n, _, w, _ in info if n != "TOC.tif"}
    checks = [
        ("Abstract ≤ 250 words", len(abstract.split()) <= 250, f"{len(abstract.split())} words"),
        ("Figures first cited in order", order["Fig"] == list(range(1, len(figs) + 1)), str(order["Fig"])),
        ("Tables first cited in order", order["Table"] == sorted(order["Table"]), str(order["Table"])),
        ("Every figure has a caption", len(caps) == len(figs), f"{len(caps)} captions, {len(figs)} figures"),
        ("SI tables S1–S5 cited in the text", si_cited == ["1", "2", "3", "4", "5"], ", ".join(si_cited)),
        ("Figures 600 dpi", all(d >= 600 for _, d, _, _ in info), ", ".join(f"{n} {d:.0f}" for n, d, _, _ in info)),
        ("Figure widths ≤ 7 in (double column)", all(w <= 7.01 for w in width.values()),
         ", ".join(f"{n} {w:.2f} in" for n, w in width.items())),
        ("TOC graphic 3.25 × 1.75 in", abs(toc[2] - 3.25) < 0.01 and abs(toc[3] - 1.75) < 0.01,
         f"{toc[2]:.2f} × {toc[3]:.2f} in"),
        ("Data and Software Availability section", "Data and Software Availability" in ps, ""),
        ("Supporting Information paragraph", any(p.startswith("Supporting Information.") for p in ps), ""),
        ("References numbered", nrefs > 0, f"{nrefs} references"),
        ("No leftover placeholders except the AI statement",
         sum("[AUTHOR TO COMPLETE" in p or "PENDING" in p for p in ps) == 1,
         f"{sum('[AUTHOR TO COMPLETE' in p or 'PENDING' in p for p in ps)} placeholder(s)"),
    ]
    lines = ["# J. Chem. Inf. Model. submission package", "",
             "Generated by `src/make_jcim_package.py`.", "", "## Automatic checks", "",
             "| Check | Result | Detail |", "|---|---|---|"]
    lines += [f"| {a} | {'OK' if b else '**FAIL**'} | {c} |" for a, b, c in checks]
    lines += ["", "## Author to do before submission", "",
              "- Write the statement on the use of AI tools (yellow placeholder in the manuscript).",
              "- Reread the manuscript, the Supporting Information and the cover letter.",
              "- Decide whether to add the glioblastoma DFT adsorption results (still running) before "
              "submitting; the paper currently reports the method failure (xTB) and the periodic-image check "
              "only.",
              "- ACS Paragon Plus: manuscript type Article; suggest reviewers if desired; upload the TOC graphic "
              "separately.",
              "- Publish the new Zenodo version (with approval) and update the Data and Software Availability "
              "DOI if the repository DOI is cited.", ""]
    (OUT / "CHECKLIST.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    return all(b for _, b, _ in checks)


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
